### ISSUE TITLE
version in query comment is not being incremented

### ISSUE THREAD

**Issue by gofford** [bqbooster/dbt-bigquery-monitoring#19]
The version number in the query comment is currently hard coded to `0.1.0`. I suspect that this should probably be incremented to the version number of the package as part of the release process. 

https://github.com/bqbooster/dbt-bigquery-monitoring/blob/7a45475f8e3a678978f257a3cf5d7f25802010a8/macros/set_query_comment.sql#L9

**Comment by Kayrnt** [comment]
Fair point, that could be bumped as well, I'll see if I can update that in the automated release workflow

**Comment by Kayrnt** [comment]
Fixed in https://github.com/bqbooster/dbt-bigquery-monitoring/pull/24 👌
