### ISSUE TITLE
No supported_languages found in materialization macro dbt_macro__materialization_view_if_explicit_projects

### ISSUE THREAD

**Issue by lee-cullen** [bqbooster/dbt-bigquery-monitoring#26]
Getting error when running `dbt run -s tag:dbt-bigquery-monitoring`:

![image](https://github.com/user-attachments/assets/2873bb24-b3dc-43b4-883b-47cae42a5581)

Appears to be introduced in 0.7.0 as 0.6.0 works fine!

**Comment by Kayrnt** [comment]
Hello @lee-cullen, thank you for reporting the issue!
It looks like it's a bug from dbt: https://github.com/dbt-labs/dbt-core/issues/6231
As you've been running a ~1 year old version, could you consider upgrading to 1.8.6 or maybe latest 1.6.X
I'll look into renaming the macro too.
