### ISSUE TITLE
Missing YML files for four storage models

### ISSUE THREAD

**Issue by nikocameron** [bqbooster/dbt-bigquery-monitoring#6]
Hi there,

Just started using your great package! We use Lightdash as our BI which validates things based upon yml files, and I was wondering whether you'd be able to generate four missing files for the following models?

```
- ERROR> dataset_with_better_pricing_on_physical_billing_model : No dimensions available
- ERROR> table_with_better_pricing_on_logical_billing_model : No dimensions available
- ERROR> table_with_better_pricing_on_physical_billing_model : No dimensions available
- ERROR> dataset_with_better_pricing_on_logical_billing_model : No dimensions available
```

All the other ones work and have them but those are missing. Thanks so much!

**Comment by github-christophe-oudar** [comment]
Hello,
yes it's in my todo list 😅
I released early those new models while fixing https://github.com/bqbooster/dbt-bigquery-monitoring/issues/4
So the data contract for those models might not be 100% stable and then I didn't write the related YML file yet 😬
I hope to be able to look at those during the weekend 👀 
Thank for reporting it and I hope you got interesting insights!

**Comment by github-christophe-oudar** [comment]
I had a lot of concurrent side projects so this one didn't get as much love as it should but I'll try to build a more complete set of datamarts over the next weeks (with some visuals for inspiration 🙌 )

**Comment by nikocameron** [comment]
How fabulous! Not necessarily the thread for this haha, but the one thing in our heads that would be great to see is being able to track the costs of dbt models more easily over time. To then see if we made a difference with efforts to reduce them

**Comment by github-christophe-oudar** [comment]
Yes that's in my thoughts, I've also some aims to track costs per dbt tag as I use it a lot to schedule sub DAGs

**Comment by Kayrnt** [comment]
I've pushed 0.5.3, let me know if it fits your need

**Comment by Kayrnt** [comment]
Great 👌 
Keep me posted if you have some ideas you'd like to see or contribute
