### ISSUE TITLE
stg_partitions_monitoring table not showing all projects and their datasets

### ISSUE THREAD

**Issue by iliasgor** [bqbooster/dbt-bigquery-monitoring#79]
Hey,

I’ve been testing this dbt package, and it looks promising. Great job! 

Till now, I’ve encountered an issue with the `stg_partitions_monitoring` table. 

Background: In the `dbt_project.yml` file, I’ve defined multiple projects that I’d like to monitor. When running the package, the data in this particular table only shows one dataset from one project. I was expecting to see all datasets from all the projects, so this might be a bug.

Let me know if you need more information—I’m happy to help! 😊

**Comment by iliasgor** [comment]
While reviewing the compiled code and testing with some data, I noticed that it doesn’t return tables from other projects due to line 13 in the model. To confirm, I ran the following query directly on the information schema for one of the projects:

```
SELECT table_catalog, table_schema, table_name, option_name, option_type, option_value
FROM `project_id`.`region-eu`.`INFORMATION_SCHEMA`.`TABLE_OPTIONS`
```

I observed that some partitioned tables in this project have an `option_name` that is not **"partition_expiration_days"** (despite being partitioned). This seems to be why those tables are excluded from the final result.

After removing line 13 from the compiled code and rerunning it, I was able to retrieve all the necessary tables. To filter only partition-related data, I added `HAVING partition_type IS NOT NULL` after the final` GROUP BY` clause.

Let me know if this helps or if you see things differently!

**Comment by Kayrnt** [comment]
Right, that's a fair point!
I guess I should replace the INNER JOIN into a LEFT JOIN.
I'll doublecheck that later today.

**Comment by Kayrnt** [comment]
I updated model in 0.14.3
let me know if that's fine.

**Comment by iliasgor** [comment]
Yes, it works! Thanks for fixing it.
